name: Sync TODO → Issues

on:
  push:
    branches:
      - '1.20.1_mcreator'
    paths:
      - 'todo.md'

jobs:
  sync:
    runs-on: ubuntu-latest

    # Achtung: Hier muss dein eigenes Secret als MY_GITHUB_TOKEN heißen
    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run sync script
        run: python sync_todo_to_issues.py
