name: Sync TODO → Issues

# Erlaube dem Standard-Token, Issues (und Projects) zu schreiben
permissions:
  contents: read        # zum Checkout & Lesen von Dateien
  issues: write         # zum Erstellen/Aktualisieren von Issues
  repository-projects: write       # zum Befüllen deines Kanban-Boards (falls genutzt)

on:
  push:
    branches:
      - '1.20.1_mcreator'
    paths:
      - 'todo.md'

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      # kein eigenes Secret mehr nötig

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install requests

      - run: python sync_todo_to_issues.py
